---
title: "White House Salaries"
resource_files:
- .httr-oauth
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: cerulean

---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(glue)
library(plotly)
library(DT)
library(googlesheets)
library(kableExtra)
library(leaflet)
# library(ggmap)
library(RColorBrewer)
library(htmlwidgets)
library(htmltools)
library(tigris)
options(tigris_class = "sf")


#import and format columns
salaries <- read_csv("whsalaries_2017_2018.csv")

salaries <- salaries %>% 
  clean_names() %>% 
  mutate(
    name = str_to_upper(name),
    last = str_to_upper(last),
    first_m = str_to_upper(first_m),
    first = str_to_upper(first),
    status = str_to_upper(status),
    paybasis = str_to_upper(paybasis),
    positiontitle = str_to_upper(positiontitle)
    )

salaries$salary <- parse_number(salaries$salary)



#### looking for those who are in both years' of data ####

yr2017 <- salaries %>% 
  filter(year == "2017")

yr2018 <- salaries %>% 
  filter(year == "2018")

joined <- inner_join(yr2017, yr2018, by = c("name" = "name"))

names(joined)

#select relevant columns and rename
joined2 <- joined %>% 
  select(
    name,
    salary2017 = salary.x,
    salary2018 = salary.y,
    title2017 = positiontitle.x,
    title2018 = positiontitle.y
    )

raises <- joined2 %>% 
  mutate(
    difference = (salary2018 - salary2017),
    pct_change = (difference/salary2017)
  ) %>% 
  select(
    name,
    salary2017,
    salary2018,
    difference,
    pct_change,
    title2017,
    title2018
  ) %>% 
  arrange(desc(pct_change))






```





2017-2018 Salaries Data 
=====================================
To filter, click on the boxes at the top of the columns. To sort, use the up/down arrows by the column names.

Row {data-height=1000}
-----------------------------------------------------------------------

```{r}

salaries_table <- salaries %>% 
  select(
    year, first_mid = first_m, last, everything(),
    -name, -first
    ) %>% 
  mutate(
    year = as.factor(year),
    paybasis = as.factor(paybasis),
    status = as.factor(status)
    )


datatable(salaries_table,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons', 
          options = list(searchHighlight = TRUE, bPaginate = FALSE, dom = 'Bfrtip',
       buttons = c('copy', 'csv', 'excel', 'print')
          )) %>% 
      formatCurrency('salary', digits = 0) %>% 
      formatStyle(c("last","first_mid", "salary"), fontWeight = 'bold') %>% 
      # formatStyle("salary", color = "darkred") %>% 
      formatStyle(
      'salary',
      background = styleColorBar(salaries_table$salary, 'steelblue'),
      backgroundSize = '100% 90%',
      backgroundRepeat = 'no-repeat',
      backgroundPosition = 'center'
    )


  # DT::formatPercentage(c('approve', 'disapprove')) %>% 
  # DT::formatStyle('approve',  color = 'darkgreen', fontWeight = 'bold') %>% 
  # DT::formatStyle('disapprove',  color = 'darkred', fontWeight = 'bold') 

```


Who got the biggest raises 
=====================================
To filter, click on the boxes at the top of the columns. To sort, use the up/down arrows by the column names.

Row {data-height=1000}
-----------------------------------------------------------------------

```{r}

datatable(raises,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons', 
          options = list(searchHighlight = TRUE, bPaginate = FALSE, dom = 'Bfrtip',
       buttons = c('copy', 'csv', 'excel', 'print')
          )) %>% 
      formatCurrency(c("salary2017", "salary2018", "difference"), digits = 0) %>% 
      formatStyle(c("name", "difference", "pct_change"), fontWeight = 'bold') %>% 
      formatPercentage("pct_change")
      # formatStyle("salary", color = "darkred") %>% 



```




Questions
=====================================
If you have any questions about these records, please contact Maegan.Vazquez@turner.com or Aaron.Kessler@turner.com. (Note: we expect the new 2019 salary figures to be available in July.)
